# Generated by Django 5.0.1 on 2024-01-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_bookin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookin',
            new_name='Booking',
        ),
    ]
